<?php

namespace Database\Seeders;

use App\Models\Room;
use Illuminate\Database\Seeder;

class RoomSeeder extends Seeder
{
    public function run(): void
    {
        $wp = 'https://www.olymposlodge.com.tr/wp-content/uploads';

        $rooms = [
            [
                'slug'           => 'aqua-super-deluxe',
                'key_prefix'     => 'asd',
                'name_tr'        => 'Aqua Super Deluxe',
                'name_en'        => 'Aqua Super Deluxe',
                'name_de'        => 'Aqua Super Deluxe',
                'description_tr' => 'Bahçenin en eşsiz odası, ucunda müstakil bir yapı olarak konumlanmış. İç mekandaki şelale duvarı ve ayaklarınızın altında suyu gösteren bir sıra cam zemin paneli tonu belirliyor.',
                'description_en' => "The garden's most extraordinary room, positioned as a detached structure at the far end. A waterfall wall inside and a row of glass floor panels revealing water beneath your feet set the tone.",
                'description_de' => 'Das außergewöhnlichste Zimmer des Gartens, als freistehendes Gebäude am Ende des Grundstücks. Eine Wasserfall-Wand im Inneren und Glasbodenplatten bestimmen den Ton.',
                'tagline_tr'     => 'Şelale, cam zemin ve kendi sessizliği.',
                'tagline_en'     => 'Waterfall wall, glass floor, its own silence.',
                'tagline_de'     => 'Wasserfall, Glasboden, eigene Stille.',
                'texts_tr'       => ['p1' => 'Bahçenin en ucunda, tesisteki diğer tüm odalardan ayrı duran müstakil bir yapı. Aqua Super Deluxe bir otel odasından çok özel bir konut. 105 metrekare, kendi verandası, kendi girişi, kendi sessizliği.', 'p2' => 'İç mekanın bir duvarı boyunca uzanan tam yükseklikte bir şelale, odayı akan suyun sabit, alçak sesiyle dolduruyor. Bir sıra cam zemin paneli, ayaklarınızın altında akan suyu gözler önüne seriyor. Etki anlık: burası sıradan bir odadan çok bir bahçe köşküne yakın hissettiriyor.', 'p3' => 'Şömine oturma alanını tanımlıyor ve serin akşamların tonunu belirliyor. Jakuzi küvet, odanın merkezine konumlandırılmış. Biri iç mekanda, biri açık havada olmak üzere iki ayrı yağmur duşu, sabah rutinini sıcaklık ile açık hava arasında bir tercihe dönüştürüyor. Espresso makinesi, minibar ve baştan sona el yapımı mobilyalar; sadece uyumak için değil, yaşamak için hazır bir oda.', 'p4' => 'Verandaya çıktığınızda bahçenin tüm derinliği önünüzde açılıyor. Buradan sahile kısa bir yürüyüş. Restorana ve spa\'ya da öyle. Ancak bu yapı, bunların hiçbirinin gerekli hissettirmeyeceği şekilde tasarlanmış. Şömineyi yakabilir, jakuziyi çalıştırabilir, kapıları açık bırakabilir ve bütün bir akşamı başka bir yerde olmanıza gerek kalmadan geçirebilirsiniz.'],
                'texts_en'       => ['p1' => 'At the far end of the garden, standing apart from every other room in the property — a detached structure. The Aqua Super Deluxe is less a hotel room than a private residence. 105 sqm, its own veranda, its own entrance, its own silence.', 'p2' => 'A full-height waterfall running along one wall fills the room with the low, steady sound of moving water. A row of glass floor panels reveals the water flowing beneath your feet. The effect is immediate: this feels less like a room than a garden pavilion.', 'p3' => 'A fireplace defines the sitting area and sets the tone for cool evenings. The jacuzzi tub is positioned at the centre of the room. Two separate rain showers — one indoors, one open-air — turn the morning routine into a choice between warmth and open sky. An espresso machine, minibar, and entirely handcrafted furniture: a room designed not just to sleep in, but to live in.', 'p4' => 'Step onto the veranda and the full depth of the garden opens before you. A short walk to the beach. The same to the restaurant and the spa. And yet this structure is designed so that none of those feel necessary. Light the fireplace, run the jacuzzi, leave the doors open, and spend an entire evening without ever needing to be somewhere else.'],
                'texts_de'       => ['p1' => 'Am äußersten Ende des Gartens, getrennt von jedem anderen Zimmer der Anlage — ein freistehendes Gebäude. Das Aqua Super Deluxe ist weniger ein Hotelzimmer als eine private Residenz. 105 m², eigene Veranda, eigener Eingang, eigene Stille.', 'p2' => 'Ein raumhoher Wasserfall entlang einer Wand füllt den Raum mit dem gleichmäßigen, leisen Geräusch fließenden Wassers. Eine Reihe von Glasbodenplatten zeigt das darunter fließende Wasser. Der Effekt ist unmittelbar: Dies fühlt sich weniger wie ein Zimmer an als wie ein Gartenpavillon.', 'p3' => 'Ein Kamin definiert den Sitzbereich und bestimmt den Ton kühler Abende. Die Whirlpool-Wanne ist im Mittelpunkt des Zimmers positioniert. Zwei separate Regenduschen — eine innen, eine im Freien — machen die Morgenroutine zur Wahl zwischen Wärme und freiem Himmel. Espressomaschine, Minibar und vollständig handgefertigte Möbel: ein Zimmer, das nicht nur zum Schlafen, sondern zum Leben geschaffen ist.', 'p4' => 'Treten Sie auf die Veranda und die ganze Tiefe des Gartens öffnet sich vor Ihnen. Ein kurzer Spaziergang zum Strand. Der gleiche zum Restaurant und zum Spa. Und doch ist dieses Gebäude so gestaltet, dass keines davon notwendig erscheint. Zünden Sie den Kamin an, lassen Sie den Whirlpool laufen, lassen Sie die Türen offen und verbringen Sie einen ganzen Abend, ohne je woanders sein zu müssen.'],
                'capacity'       => 2,
                'size_sqm'       => 105,
                'bed_type'       => 'Queen',
                'view'           => 'garden_sea',
                'amenities'      => [
                    'amenity_ac', 'amenity_terrace', 'amenity_sea',
                    'amenity_fireplace', 'amenity_jacuzzi', 'amenity_rain_shower_in_out',
                    'amenity_espresso', 'amenity_kettle', 'amenity_minibar',
                    'amenity_safe', 'amenity_wifi',
                ],
                'images' => [
                    'hero'      => "$wp/2024/11/olympos-lodge-aqua-super-deluxe-oda-2.jpg",
                    'full1'     => "$wp/2024/11/olympos-lodge-super-deluxe-double-room-6.jpg",
                    'ed1_inset' => "$wp/2024/11/IMG_5150.jpg",
                    'ed1_right' => "$wp/2024/11/olympos-lodge-aqua-super-deluxe-oda-2.jpg",
                    'full2'     => "$wp/2025/04/IMG_5376-1.jpg",
                    'ed2_inset' => "$wp/2024/11/IMG_5400.jpg",
                    'ed2_right' => "$wp/2024/11/olympos-lodge-super-deluxe-double-room-6.jpg",
                    'strip'     => [
                        "$wp/2024/11/olympos-lodge-super-deluxe-double-room-6.jpg",
                        "$wp/2025/04/IMG_5376-1.jpg",
                        "$wp/2024/11/IMG_5400.jpg",
                    ],
                ],
                'sort_order' => 1,
                'is_active'  => true,
            ],
            [
                'slug'           => 'super-deluxe',
                'key_prefix'     => 'sd',
                'name_tr'        => 'Super Deluxe',
                'name_en'        => 'Super Deluxe',
                'name_de'        => 'Super Deluxe',
                'description_tr' => 'Her yönüyle ferah, Super Deluxe geniş özel terası aracılığıyla doğrudan ön bahçeye açılıyor; deniz ağaçların arasından süzülüyor. Jakuzi küvet uzun akşamlara davet ediyor.',
                'description_en' => 'Spacious in every sense, the Super Deluxe opens directly onto the front garden via a generous private terrace — the sea filters through the trees. The jacuzzi bathtub invites long evenings.',
                'description_de' => 'In jeder Hinsicht geräumig, öffnet sich das Super Deluxe über eine großzügige private Terrasse direkt auf den Vorgarten — das Meer schimmert durch die Bäume.',
                'tagline_tr'     => 'Bahçe kapıda, deniz ağaçların ardında.',
                'tagline_en'     => 'Garden at the door, sea beyond the trees.',
                'tagline_de'     => 'Garten vor der Tür, Meer hinter den Bäumen.',
                'texts_tr'       => ['p1' => 'Her yönüyle ferah, Super Deluxe ön bahçenin tam karşısında konumlanan bir oda. 105 metrekare ve geniş özel terası aracılığıyla doğrudan bahçeye açılıyor; deniz ağaçların arasından süzülüyor.', 'p2' => 'Sabah ışığı perdelerden süzülür, yeşilin tüm tonlarını odaya taşır. Teras kapısını açtığınızda bahçe size ait olur. Rafinedir ama gösterişsiz; her detay bir şeyi söylüyor, ama bağırmıyor.', 'p3' => 'Şömine oturma alanını tanımlıyor; serin gecelerde oda farklı bir sıcaklık kazanır. Jakuzi küvet yağmur duşuyla birlikte geliyor. Espresso makinesi, minibar ve baştan sona el yapımı mobilyalar. İçeride kalmak için hiçbir şeye dışarı ihtiyacınız yok.', 'p4' => 'Dışarı çıkmak kadar içeride kalmak için de tasarlanmış bir oda. Bahçe kapıda; sahil birkaç adım ötede. Ama teras sandalyesine oturup sabahın durmasına izin vermek de tam anlamıyla yeterli.'],
                'texts_en'       => ['p1' => 'Spacious in every sense, the Super Deluxe sits directly opposite the front garden. 105 sqm, opening directly onto the garden through a generous private terrace — the sea filters through the trees.', 'p2' => 'Morning light filters through the curtains, bringing all the shades of green into the room. Open the terrace door and the garden becomes yours. Refined without being showy; every detail says something, but nothing shouts.', 'p3' => 'A fireplace defines the living area — on cool nights the room takes on a different warmth. The jacuzzi comes with a rain shower. An espresso machine, minibar, and entirely handcrafted furniture. You need nothing outside to stay inside.', 'p4' => 'A room designed as much for staying in as for going out. The garden is at the door; the beach a few steps beyond. But sitting on the terrace and letting the morning stand still is entirely enough.'],
                'texts_de'       => ['p1' => 'In jeder Hinsicht geräumig, liegt das Super Deluxe direkt gegenüber dem Vorgarten. 105 m², über eine großzügige private Terrasse direkt auf den Garten öffnend — das Meer filtert durch die Bäume.', 'p2' => 'Das Morgenlicht filtert durch die Vorhänge und bringt alle Grüntöne ins Zimmer. Öffnen Sie die Terrassentür und der Garten gehört Ihnen. Verfeinert ohne Zurschaustellung; jedes Detail sagt etwas, aber nichts schreit.', 'p3' => 'Ein Kamin definiert den Wohnbereich — an kühlen Nächten gewinnt das Zimmer eine andere Wärme. Der Whirlpool kommt mit Regendusche. Espressomaschine, Minibar und vollständig handgefertigte Möbel. Sie brauchen nichts draußen, um drinnen zu bleiben.', 'p4' => 'Ein Zimmer, das ebenso sehr zum Drinbleiben wie zum Rausgehen gestaltet ist. Der Garten liegt direkt vor der Tür; der Strand wenige Schritte entfernt. Aber auf der Terrasse sitzen und den Morgen innehalten zu lassen ist vollkommen genug.'],
                'capacity'       => 2,
                'size_sqm'       => 105,
                'bed_type'       => 'Queen',
                'view'           => 'garden',
                'amenities'      => [
                    'amenity_ac', 'amenity_terrace', 'amenity_garden',
                    'amenity_fireplace', 'amenity_jacuzzi', 'amenity_rain_shower',
                    'amenity_espresso', 'amenity_furniture', 'amenity_minibar', 'amenity_wifi',
                ],
                'images' => [
                    'hero'      => "$wp/2024/11/olympos-lodge-super-deluxe-double-room-7.jpg",
                    'full1'     => "$wp/2024/11/olympos-lodge-super-deluxe-double-room-7.jpg",
                    'ed1_inset' => "$wp/2024/11/olympos-lodge-super-deluxe-double-room-6.jpg",
                    'ed1_right' => "$wp/2024/11/olympos-lodge-super-deluxe-double-room-7.jpg",
                    'full2'     => "$wp/2025/04/IMG_5376-1.jpg",
                    'ed2_inset' => "$wp/2024/11/IMG_5400.jpg",
                    'ed2_right' => "$wp/2024/11/olympos-lodge-super-deluxe-double-room-6.jpg",
                    'strip'     => [
                        "$wp/2024/11/olympos-lodge-super-deluxe-double-room-6.jpg",
                        "$wp/2025/04/IMG_5376-1.jpg",
                        "$wp/2024/11/IMG_5400.jpg",
                    ],
                ],
                'sort_order' => 2,
                'is_active'  => true,
            ],
            [
                'slug'           => 'deluxe',
                'key_prefix'     => 'dx',
                'name_tr'        => 'Deluxe',
                'name_en'        => 'Deluxe',
                'name_de'        => 'Deluxe',
                'description_tr' => 'Bir konut kadar ferah, bir sığınak kadar samimi. Deluxe, jakuzi ve şömineyi bahçeye bakan geniş bir terasla buluşturuyor.',
                'description_en' => 'As spacious as a home, as intimate as a hideaway. The Deluxe pairs a jacuzzi and fireplace with a generous garden-facing terrace.',
                'description_de' => 'So geräumig wie ein Zuhause, so intim wie ein Rückzugsort. Das Deluxe verbindet Whirlpool und Kamin mit einer großzügigen Terrasse mit Gartenblick.',
                'tagline_tr'     => 'Jakuzi, şömine ve bahçeye açılan teras.',
                'tagline_en'     => 'Jacuzzi, fireplace and a garden-facing terrace.',
                'tagline_de'     => 'Whirlpool, Kamin und Gartenterrasse.',
                'texts_tr'       => ['p1' => 'Bir konut kadar ferah, bir sığınak kadar samimi. Deluxe, jakuzi ve şömineyi bahçeye bakan geniş bir terasla buluşturuyor. 70 metrekare, her şeyin yerinde olduğu, hiçbir şeyin gereğinden fazla olmadığı bir oda.', 'p2' => 'Akdeniz ışığı mekanın büyük bir kısmını üstleniyor; mobilyalar onunla konuşuyor. Teras, sabah kahvesi için, öğleden sonra kitap için, akşam bir kadeh şarap için eşit derecede uygun.', 'p3' => 'Şömine soğuk gecelere karakter katıyor. Jakuzi küvet standart bir banyonun çok ötesine taşıyor. Espresso makinesi ve minibar günü kendi hızınızda başlatmanızı sağlıyor. Deluxe, lüks ile sadeliğin çelişmediğini kanıtlayan bir oda.', 'p4' => 'Aynı bahçe, biraz daha derine. Deluxe\'ün terası hem içeriye hem dışarıya bakıyor. Sahile birkaç dakika, ormanın sesine anında. İçeri girdiğinizde, dışarıda ne olduğu önemini yitiriyor.'],
                'texts_en'       => ['p1' => 'As spacious as a home, as intimate as a hideaway. The Deluxe pairs a jacuzzi and fireplace with a generous garden-facing terrace. 70 sqm — everything in its place, nothing in excess.', 'p2' => 'Mediterranean light takes charge of much of the space; the furniture converses with it. The terrace works equally well for morning coffee, an afternoon book, and an evening glass of wine.', 'p3' => 'The fireplace gives cool nights their character. The jacuzzi tub goes well beyond a standard bath. An espresso machine and minibar let the day start at its own pace. The Deluxe proves that luxury and simplicity are not opposites.', 'p4' => 'The same garden, a little deeper. The Deluxe terrace looks both inward and outward. Minutes to the beach, the sound of the forest immediately. Once inside, what\'s outside becomes beside the point.'],
                'texts_de'       => ['p1' => 'So geräumig wie ein Zuhause, so intim wie ein Rückzugsort. Das Deluxe verbindet Whirlpool und Kamin mit einer großzügigen Terrasse mit Gartenblick. 70 m² — alles an seinem Platz, nichts im Übermaß.', 'p2' => 'Mediterranes Licht übernimmt einen Großteil des Raums; die Möbel unterhalten sich damit. Die Terrasse eignet sich gleichermaßen für den Morgenkaffee, ein Buch nachmittags und ein Abendglas Wein.', 'p3' => 'Der Kamin verleiht kühlen Nächten ihren Charakter. Die Whirlpool-Wanne geht weit über ein gewöhnliches Bad hinaus. Espressomaschine und Minibar lassen den Tag in eigenem Tempo beginnen. Das Deluxe beweist, dass Luxus und Schlichtheit keine Gegensätze sind.', 'p4' => 'Derselbe Garten, etwas tiefer. Die Deluxe-Terrasse blickt sowohl nach innen als auch nach außen. Minuten zum Strand, der Klang des Waldes sofort. Einmal drinnen, wird das Draußen zur Nebensache.'],
                'capacity'       => 2,
                'size_sqm'       => 70,
                'bed_type'       => 'Queen',
                'view'           => 'garden',
                'amenities'      => [
                    'amenity_ac', 'amenity_terrace', 'amenity_garden',
                    'amenity_fireplace', 'amenity_jacuzzi', 'amenity_rain_shower',
                    'amenity_espresso', 'amenity_minibar', 'amenity_wifi',
                ],
                'images' => [
                    'hero'      => "$wp/2024/11/olympos-lodge-deluxe-double-room-1-890x664.jpg",
                    'full1'     => "$wp/2024/11/olympos-lodge-deluxe-double-room-1-890x664.jpg",
                    'ed1_inset' => "$wp/2024/11/olympos-lodge-super-deluxe-double-room-6.jpg",
                    'ed1_right' => "$wp/2024/11/olympos-lodge-deluxe-double-room-1-890x664.jpg",
                    'full2'     => "$wp/2025/04/IMG_5376-1.jpg",
                    'ed2_inset' => "$wp/2024/11/IMG_5400.jpg",
                    'ed2_right' => "$wp/2024/11/olympos-lodge-super-deluxe-double-room-6.jpg",
                    'strip'     => [
                        "$wp/2024/11/olympos-lodge-deluxe-double-room-1-890x664.jpg",
                        "$wp/2025/04/IMG_5376-1.jpg",
                        "$wp/2024/11/IMG_5150.jpg",
                    ],
                ],
                'sort_order' => 3,
                'is_active'  => true,
            ],
            [
                'slug'           => 'gol-evi',
                'key_prefix'     => 'ge',
                'name_tr'        => 'Göl Evi',
                'name_en'        => 'Lake House',
                'name_de'        => 'Seehaus',
                'description_tr' => 'Tesisin geri kalanından ayrı konumlanan müstakil bir oda; terasın ötesinde bir gölet uzanıyor. Yüzeyi bahçenin ışığını, aydınlık gecelerde ise ayı ikiye katlıyor.',
                'description_en' => 'A detached room set apart from the rest of the property; beyond the terrace lies a pond. Its surface doubles the garden light — and on clear nights, the moon.',
                'description_de' => 'Ein freistehendes Zimmer abseits vom Rest der Anlage; jenseits der Terrasse erstreckt sich ein Teich. Seine Oberfläche spiegelt das Gartenlicht — und an klaren Nächten den Mond.',
                'tagline_tr'     => 'Göletin yansımasında bahçe ve gökyüzü.',
                'tagline_en'     => 'Garden and sky reflected in the pond.',
                'tagline_de'     => 'Garten und Himmel im Teich gespiegelt.',
                'texts_tr'       => ['p1' => 'Tesisin geri kalanından ayrı konumlanan müstakil bir oda; terasın ötesinde bir gölet uzanıyor. Yüzeyi bahçenin ışığını, aydınlık gecelerde ise ayı ikiye katlıyor. Göl Evi, mahremiyet ve doğayla başka türlü bir ilişki sunuyor.', 'p2' => 'Şömineli iç mekan, mahremiyetini mimarinin içine işlemiş olanlar için kendi başına yeten bir dünya tamamlıyor. Sabah, gölün yüzeyindeki yansımalar odanın tavanına taşınıyor. Akşam, ışık yavaşça kararıyor ve yalnızca ateşin titremesi kalıyor.', 'p3' => 'Göl Evi\'nin konforu sadeliğinde saklı. Yağmur duşu, espresso makinesi, minibar: gerekli olan her şey var. Fazlası yok. Doğayla kurulan ilişki bu odada mimarinin ötesine geçiyor; gölet, her gün farklı bir tablo sunuyor.', 'p4' => 'Sabah terasın kapısını açın. Gölet sessizce bekliyordur. Bahçenin sesi, ormanın kokusu, suyun yansıması. Göl Evi\'nde bir gün başlamak, başka bir yerde başlamaktan farklı hissettiriyor.'],
                'texts_en'       => ['p1' => 'A detached room set apart from the rest of the property; beyond the terrace lies a pond. Its surface doubles the garden light — and on clear nights, the moon. The Lake House offers a different kind of relationship with privacy and nature.', 'p2' => 'The fireplace in the interior completes a world that is entirely self-sufficient for those who\'ve embedded their sense of privacy in the architecture. In the morning, reflections from the pond\'s surface travel to the ceiling. In the evening, the light slowly fades and only the flicker of the fire remains.', 'p3' => 'The comfort of the Lake House is in its simplicity. Rain shower, espresso machine, minibar — everything necessary. Nothing more. The relationship with nature goes beyond architecture here; the pond offers a different composition each day.', 'p4' => 'Open the terrace door in the morning. The pond will be there, quiet. The sound of the garden, the scent of the forest, the reflection of the water. Starting a day at the Lake House feels different from starting one anywhere else.'],
                'texts_de'       => ['p1' => 'Ein freistehendes Zimmer, das sich vom Rest der Anlage absetzt; jenseits der Terrasse liegt ein Teich. Seine Oberfläche verdoppelt das Gartenlicht — und an klaren Nächten den Mond. Das Seehaus bietet eine andere Art von Beziehung zu Privatsphäre und Natur.', 'p2' => 'Der Kamin im Inneren vervollständigt eine Welt, die für diejenigen vollständig in sich selbst ist, die ihr Gefühl für Privatsphäre in die Architektur eingebettet haben. Morgens wandern die Reflexionen von der Teichwasseroberfläche an die Zimmerdecke. Abends lässt das Licht langsam nach und nur das Flackern des Feuers bleibt.', 'p3' => 'Der Komfort des Seehauses liegt in seiner Schlichtheit. Regendusche, Espressomaschine, Minibar — alles Notwendige. Nichts mehr. Die Beziehung zur Natur geht hier über die Architektur hinaus; der Teich bietet täglich eine andere Komposition.', 'p4' => 'Öffnen Sie die Terrassentür am Morgen. Der Teich wird still da sein. Der Klang des Gartens, der Duft des Waldes, die Reflexion des Wassers. Den Tag im Seehaus zu beginnen fühlt sich anders an als anderswo.'],
                'capacity'       => 2,
                'size_sqm'       => 60,
                'bed_type'       => 'Queen',
                'view'           => 'lake',
                'amenities'      => [
                    'amenity_ac', 'amenity_terrace', 'amenity_lake',
                    'amenity_fireplace', 'amenity_rain_shower',
                    'amenity_espresso', 'amenity_minibar', 'amenity_wifi',
                ],
                'images' => [
                    'hero'      => "$wp/2025/11/Lake-House-Deluxe-room-9.jpg",
                    'full1'     => "$wp/2025/11/Lake-House-Deluxe-room-9.jpg",
                    'ed1_inset' => "$wp/2024/11/IMG_5150.jpg",
                    'ed1_right' => "$wp/2025/11/Lake-House-Deluxe-room-9.jpg",
                    'full2'     => "$wp/2025/04/IMG_5376-1.jpg",
                    'ed2_inset' => "$wp/2024/11/IMG_5400.jpg",
                    'ed2_right' => "$wp/2025/11/Lake-House-Deluxe-room-9.jpg",
                    'strip'     => [
                        "$wp/2025/11/Lake-House-Deluxe-room-9.jpg",
                        "$wp/2025/04/IMG_5376-1.jpg",
                        "$wp/2024/11/IMG_5150.jpg",
                    ],
                ],
                'sort_order' => 4,
                'is_active'  => true,
            ],
            [
                'slug'           => 'antik',
                'key_prefix'     => 'an',
                'name_tr'        => 'Antik Oda',
                'name_en'        => 'Antique Room',
                'name_de'        => 'Antikes Zimmer',
                'description_tr' => 'Merkezde pirinç bir karyola; etrafında onlarca yılda özenle toplanmış antika mobilyalar ve zamanın ağırlığını taşıyan objeler.',
                'description_en' => 'At its centre, a brass bed; around it, antique furniture and objects gathered carefully over decades, each carrying the weight of time.',
                'description_de' => 'Im Mittelpunkt ein Messingbett; drum herum über Jahrzehnte sorgfältig gesammelte Antiquitäten und Objekte, die die Last der Zeit in sich tragen.',
                'tagline_tr'     => 'Zamanın ağırlığını taşıyan bir oda.',
                'tagline_en'     => 'A room that carries the weight of time.',
                'tagline_de'     => 'Ein Zimmer, das die Last der Zeit trägt.',
                'texts_tr'       => ['p1' => 'Merkezde pirinç bir karyola; etrafında onlarca yılda özenle toplanmış antika mobilyalar ve zamanın ağırlığını taşıyan objeler. Antik Oda, bir koleksiyonun içinde uyumak gibi hissettiriyor.', 'p2' => 'Bahçenin tamamen size ait hissettirdiği sessiz bir köşeye sığınmış, derin bir durgunluğa açılan terasla birleşiyor. Burada hiçbir şey dün gelmiş gibi görünmüyor; her obje bir yolculuktan döndü ve buraya yerleşti.', 'p3' => 'Klima, yağmur duşu, minibar ve Wi-Fi: modern konfor, tarihin içinde sızıntısız bir şekilde yerini buluyor. Antik Oda, geriye dönmek değil; geçmişin birikimini bugünün konforu ile buluşturmak üzerine kurulu.', 'p4' => 'Antik Oda\'da zaman farklı akar. Sabah bu mobilyalara bakarak güne başlamak, masal gibi hissettiriyor. Teras, bahçeye açılıyor; bahçe, denize. Her şey birbirine bağlı ama hiçbir şey birbirini zorlamıyor.'],
                'texts_en'       => ['p1' => 'At the centre, a brass bed; around it, antique furniture and objects gathered carefully over decades, each carrying the weight of time. Sleeping in the Antique Room feels like sleeping inside a collection.', 'p2' => 'Nestled in a quiet corner of the garden that feels entirely your own, it connects to a terrace that opens onto deep stillness. Nothing here looks like it arrived yesterday; every object completed a journey before finding its place.', 'p3' => 'Air conditioning, rain shower, minibar, and Wi-Fi: modern comfort finds its place inside history without friction. The Antique Room is not about going back; it\'s about bringing the accumulated weight of the past into contact with today\'s ease.', 'p4' => 'Time moves differently in the Antique Room. Starting the day by looking at these pieces of furniture feels like something out of a story. The terrace opens to the garden; the garden opens to the sea. Everything is connected, but nothing forces anything.'],
                'texts_de'       => ['p1' => 'Im Mittelpunkt ein Messingbett; drum herum über Jahrzehnte sorgfältig gesammelte Antiquitäten und Objekte, die die Last der Zeit in sich tragen. Im Antiken Zimmer zu schlafen fühlt sich an wie das Schlafen in einer Sammlung.', 'p2' => 'In einer stillen Ecke des Gartens untergebracht, die sich vollständig eigen anfühlt, verbindet es sich mit einer Terrasse, die in tiefe Stille öffnet. Nichts hier sieht aus, als wäre es gestern angekommen; jedes Objekt vollendete eine Reise, bevor es seinen Platz fand.', 'p3' => 'Klimaanlage, Regendusche, Minibar und WLAN: moderner Komfort findet reibungslos seinen Platz innerhalb der Geschichte. Das Antike Zimmer dreht sich nicht ums Zurückgehen; es geht darum, das angesammelte Gewicht der Vergangenheit in Kontakt mit dem heutigen Komfort zu bringen.', 'p4' => 'Die Zeit vergeht anders im Antiken Zimmer. Den Tag mit dem Blick auf diese Möbel zu beginnen fühlt sich wie aus einer Geschichte an. Die Terrasse öffnet zum Garten; der Garten öffnet zum Meer. Alles ist verbunden, aber nichts zwingt etwas.'],
                'capacity'       => 2,
                'size_sqm'       => null,
                'bed_type'       => 'Queen Brass',
                'view'           => 'garden',
                'amenities'      => [
                    'amenity_ac', 'amenity_terrace', 'amenity_garden',
                    'amenity_rain_shower', 'amenity_minibar', 'amenity_wifi',
                ],
                'images' => [
                    'hero'      => "$wp/2024/11/olympos-lodge-antique-room-3.jpg",
                    'full1'     => "$wp/2024/11/olympos-lodge-antique-room-3.jpg",
                    'ed1_inset' => "$wp/2024/11/IMG_5510-1.jpg",
                    'ed1_right' => "$wp/2024/11/olympos-lodge-antique-room-3.jpg",
                    'full2'     => "$wp/2024/11/MG_7191.jpg",
                    'ed2_inset' => "$wp/2024/11/IMG_5400.jpg",
                    'ed2_right' => "$wp/2024/11/olympos-lodge-antique-room-3.jpg",
                    'strip'     => [
                        "$wp/2024/11/olympos-lodge-antique-room-3.jpg",
                        "$wp/2024/11/IMG_5510-1.jpg",
                        "$wp/2024/11/MG_7191.jpg",
                    ],
                ],
                'sort_order' => 5,
                'is_active'  => true,
            ],
            [
                'slug'           => 'standart',
                'key_prefix'     => 'st',
                'name_tr'        => 'Standart Oda',
                'name_en'        => 'Standard Room',
                'name_de'        => 'Standardzimmer',
                'description_tr' => 'Sade çizgiler, çift kişilik yatak ve bahçe manzaralı özel teras. İhtiyacınız olan her şey var, araya giren hiçbir şey yok.',
                'description_en' => 'Clean lines, a double bed and a private terrace looking onto the garden. Everything you need; nothing in the way.',
                'description_de' => 'Klare Linien, ein Doppelbett und eine private Terrasse mit Gartenblick. Alles, was Sie brauchen; nichts, das im Weg steht.',
                'tagline_tr'     => 'Sadelik ve cömertlik arasındaki denge.',
                'tagline_en'     => 'The balance between simplicity and generosity.',
                'tagline_de'     => 'Die Balance zwischen Schlichtheit und Großzügigkeit.',
                'texts_tr'       => ['p1' => 'Sade çizgiler, çift kişilik yatak ve bahçe manzaralı özel teras. Standart Oda, ihtiyacınız olan her şeyi sunuyor; araya giren hiçbir şey yok. Sadelik ile cömertliğin zıt olmadığını kanıtlayan bir oda.', 'p2' => 'Sabah ışığı terastan giriyor, güne doğal bir başlangıç yapıyor. Yağmur duşundan sonra bir espresso; bu ritme alıştıktan sonra başka bir şey gerekmiyor. Standart Oda, minimalist olmak zorunda kalmadan sade olmanın mümkün olduğunu gösteriyor.', 'p3' => 'Klima, yağmur duşu, minibar ve Wi-Fi; hepsi yerinde. Bahçe manzaralı teras, güne başlamak için en iyi sebebi sunuyor. 35 metrekare, doğru tasarımla ihtiyaç duyulan her şeyi barındırıyor.', 'p4' => 'Standart Oda, Olympos Lodge\'un ruhunu en saf haliyle taşıyor. Bahçe kapıda, plaj ötede. Teras sandalyesine oturun; geri kalanı kendiliğinden yerli yerine oturuyor.'],
                'texts_en'       => ['p1' => 'Clean lines, a double bed, and a private terrace with a garden view. The Standard Room gives you everything you need and nothing in the way. A room that proves simplicity and generosity are not opposites.', 'p2' => 'Morning light enters from the terrace — a natural start to the day. A rain shower, then an espresso; once this rhythm sets in, nothing else is needed. The Standard Room shows that being simple doesn\'t require being minimal.', 'p3' => 'Air conditioning, rain shower, minibar, and Wi-Fi — all present. The garden-view terrace offers the best reason to start the day. 35 sqm; the right design holds everything necessary.', 'p4' => 'The Standard Room carries the spirit of Olympos Lodge in its purest form. The garden is at the door, the beach beyond. Sit on the terrace; the rest falls naturally into place.'],
                'texts_de'       => ['p1' => 'Klare Linien, ein Doppelbett und eine private Terrasse mit Gartenblick. Das Standardzimmer gibt Ihnen alles, was Sie brauchen, und nichts, das im Weg steht. Ein Zimmer, das beweist, dass Schlichtheit und Großzügigkeit keine Gegensätze sind.', 'p2' => 'Das Morgenlicht kommt von der Terrasse — ein natürlicher Tagesanfang. Eine Regendusche, dann ein Espresso; wenn sich dieser Rhythmus eingestellt hat, wird nichts anderes gebraucht. Das Standardzimmer zeigt, dass Einfachsein keine Minimalismus erfordert.', 'p3' => 'Klimaanlage, Regendusche, Minibar und WLAN — alles vorhanden. Die Terrasse mit Gartenblick bietet den besten Grund, den Tag zu beginnen. 35 m²; das richtige Design birgt alles Notwendige.', 'p4' => 'Das Standardzimmer trägt den Geist des Olympos Lodge in seiner reinsten Form. Der Garten liegt direkt vor der Tür, der Strand dahinter. Setzen Sie sich auf die Terrasse; der Rest fügt sich ganz von selbst.'],
                'capacity'       => 2,
                'size_sqm'       => 35,
                'bed_type'       => 'Double',
                'view'           => 'garden',
                'amenities'      => [
                    'amenity_ac', 'amenity_terrace', 'amenity_garden',
                    'amenity_rain_shower', 'amenity_minibar', 'amenity_wifi',
                ],
                'images' => [
                    'hero'      => "$wp/2024/11/olympos-lodge-double-room-1.jpg",
                    'full1'     => "$wp/2024/11/olympos-lodge-double-room-1.jpg",
                    'ed1_inset' => "$wp/2024/11/olympos-lodge-super-deluxe-double-room-6.jpg",
                    'ed1_right' => "$wp/2024/11/olympos-lodge-double-room-1.jpg",
                    'full2'     => "$wp/2025/04/IMG_5376-1.jpg",
                    'ed2_inset' => "$wp/2024/11/IMG_5400.jpg",
                    'ed2_right' => "$wp/2024/11/olympos-lodge-double-room-1.jpg",
                    'strip'     => [
                        "$wp/2024/11/olympos-lodge-double-room-1.jpg",
                        "$wp/2025/04/IMG_5376-1.jpg",
                        "$wp/2024/11/olympos-lodge-super-deluxe-double-room-6.jpg",
                    ],
                ],
                'sort_order' => 6,
                'is_active'  => true,
            ],
        ];

        foreach ($rooms as $data) {
            Room::updateOrCreate(['slug' => $data['slug']], $data);
        }

        $prices = [
            'aqua-super-deluxe' => 320,
            'super-deluxe'      => 220,
            'deluxe'            => 180,
            'gol-evi'           => 260,
            'antik'             => 150,
            'standart'          => 120,
        ];
        foreach ($prices as $slug => $price) {
            Room::where('slug', $slug)->update(['price_per_night' => $price]);
        }
    }
}
